<?php

// 在 admin_index.php 中使用的语言定义
$lang_admin_index = array(

'fopen disabled message'         => '由于系统中禁用了 \'allow_url_fopen\'，无法检查升级。',
'Upgrade check failed message'   => '由于未知原因，升级检查失败。',
'Running latest version message' => '您正在运行 FluxBB 的最新版本。',
'New version available message'  => 'FluxBB 的新版本已发布。您可以在 %s 下载最新版本。',
'Deleted install.php redirect'   => '文件已成功删除。正在重定向 …',
'Delete install.php failed'      => '无法删除 install.php，请手动执行。',
'Not available'                  => '不可用',
'Forum admin head'               => '论坛管理',
'NA'                             => '不适用',
'Welcome to admin'               => '欢迎来到 FluxBB 管理控制面板。从这里，您可以控制论坛的重要方面。根据您的身份是管理员还是版主，您可以：',
'Welcome 1'                      => '组织分类和论坛。',
'Welcome 2'                      => '设置论坛范围的选项和偏好。',
'Welcome 3'                      => '控制用户和访客的权限。',
'Welcome 4'                      => '查看用户的 IP 统计信息。',
'Welcome 5'                      => '禁止用户。',
'Welcome 6'                      => '审查词语。',
'Welcome 7'                      => '设置用户组和晋升。',
'Welcome 8'                      => '修剪旧帖子。',
'Welcome 9'                      => '处理帖子报告。',
'Alerts head'                    => '警告',
'Install file exists'            => 'install.php 文件仍然存在，但它应该被删除。%s。',
'Delete install file'            => '删除它',
'About head'                     => '关于 FluxBB',
'FluxBB version label'           => 'FluxBB 版本',
'Check for upgrade'              => '检查升级',
'FluxBB version data'            => '版本 v %s',
'Server statistics label'        => '服务器统计',
'View server statistics'         => '查看服务器统计',
'Support label'                  => '支持',
'Forum label'                    => '论坛',
'IRC label'                      => 'IRC 频道',

// 在 admin_statistics.php 中使用的语言定义
'PHPinfo disabled message'       => 'PHP 函数 phpinfo() 在此服务器上已被禁用。',
'Server statistics head'         => '服务器统计',
'Server load label'              => '服务器负载',
'Server load data'               => '%s - %s 用户在线',
'Environment label'              => '环境',
'Environment data OS'            => '操作系统：%s',
'Show info'                      => '显示信息',
'Environment data version'       => 'PHP：%s - %s',
'Environment data acc'           => '加速器：%s',
'Database label'                 => '数据库',
'Database data rows'             => '行数：%s',
'Database data size'             => '大小：%s',

);
