<?php

// 在 admin_plugin_smilies.php 中使用的语言定义
$lang_smiley = array(

'Create Smiley Code None'       => '您必须提供一个文本代码。',
'Create Smiley Image None'     => '您必须提供一张图片。',
'Code already exists'           => '文本代码已经存在。',
'Images affected'              => '以下图片不能被删除，因为它们正在使用中：%s <br />要删除它们，请从表情符号列表中移除它们。',
'Images not deleted'           => '由于未知原因，以下图片未被删除：%s',
'Description'                  => '此插件允许您管理论坛的表情符号。',
'Submit New Smiley'            => '创建新表情符号',
'Add Images Smilies'          => '添加新图片',
'Smiley Code'                  => '文本代码',
'Smiley Image'                 => '图片文件名',
'Smiley Code Description'     => '输入您希望表情符号显示的文本代码（例如: :O）。',
'Smiley Image Description'     => '从列表中选择一个与上述文本代码相对应的图片（例如: bignose.png）。',
'Choose Image'                 => '&lt;选择一张图片&gt;',
'Submit Smiley'               => '创建表情符号',
'Upload'                       => '上传',
'Delete Smiley Redirect'       => '表情符号已成功删除。正在重定向 …',
'No Smileys'                   => '未选择表情符号。',
'Images deleted'               => '图片已成功删除。正在重定向 …',
'No Images'                    => '未选择图片。',
'Successful Creation'          => '您已成功创建了新的表情符号。正在重定向 …',
'Successful Upload'            => '图片成功上传。正在重定向 …',
'Current Smilies'              => '当前表情符号',
'Current Images'               => '当前可用图片',
'List Current Smilies'        => '当前表情符号列表',
'List Images Smilies'          => '当前图片列表',
'Code'                         => '代码',
'Image'                        => '图片',
'Image Filename'               => '图片文件名',
'Delete'                       => '删除',
'Delete Selected'             => '删除选定的图片',
'Remove'                       => '移除',
'Remove Selected'             => '移除选定的表情符号',
'No smiley'                    => '没有表情符号。',
'Too large ini'                => '所选文件太大，无法上传。服务器不允许上传。',
'Partial upload'               => '所选文件只上传了部分。请重试。',
'No tmp directory'             => 'PHP 无法将上传的文件保存到临时位置。',
'No file'                      => '您没有选择要上传的文件。',
'Bad type'                     => '您尝试上传的文件类型不允许。允许的类型有 gif、jpeg 和 png。',
'Too wide or high'            => '您尝试上传的文件比允许的最大尺寸宽和/或高：',
'Too large'                     => '您尝试上传的文件比允许的最大大小大：',
'pixels'                       => '像素',
'bytes'                        => '字节',
'Move failed'                  => '服务器无法保存上传的文件。',
'Unknown failure'               => '发生了未知错误。请重试。',
'Image file'                   => '图片文件',
'Position'                     => '位置',
'Edit smilies'                 => '编辑所有表情符号',
'Duplicate smilies code'       => '不能在两个表情符号上重复代码 %s。',
'Smilies edited'              => '表情符号已成功编辑。正在重定向 …'

);
