<?php

// 在 admin_users.php 中使用的语言定义
$lang_admin_users = array(

'Non numeric message'       => '您在仅限数字的列中输入了非数字值。',
'Invalid date time message' => '您输入的日期/时间无效。',
'Not verified'              => '未验证',

// 操作：批量删除/禁止等
'No users selected'         => '未选择用户。',
'No move admins message'    => '出于安全原因，您不能将多个管理员移动到另一个用户组。如果您想移动这些管理员，可以在他们各自的用户资料中这样做。',
'No delete admins message'  => '管理员不能被删除。要删除管理员，您必须先将他们移动到不同的用户组。',
'No ban admins message'     => '管理员不能被禁止。要禁止管理员，您必须先将他们移动到不同的用户组。',
'No ban mods message'       => '版主不能被禁止。要禁止版主，您必须先将他们移动到不同的用户组。',
'Move users'                => '更改用户组',
'Move users subhead'        => '选择新的用户组',
'New group label'           => '新用户组',
'New group help'            => '选择要将选定用户移动到的组。出于安全原因，不可能将多个用户移动到管理员组。',
'Invalid group message'     => '无效的用户组ID。',
'Users move redirect'       => '用户组已更改。正在重定向 …',
'Delete users'              => '删除用户',
'Confirm delete legend'     => '重要：在删除前阅读',
'Confirm delete info'       => '请确认您想要删除这些用户。',
'Delete posts'              => '删除这些用户发表的任何帖子和主题。',
'Delete warning'            => '警告！删除的用户和/或帖子无法恢复。如果您选择不删除这些用户发表的帖子，这些帖子只能在以后手动删除。',
'Users delete redirect'     => '用户已删除。正在重定向 …',
'Ban users'                 => '禁止用户',
'Message expiry subhead'    => '禁止消息和到期',
'Ban message label'         => '禁止消息',
'Ban message help'          => '当被禁止的用户访问论坛时，将向他们显示的消息。',
'Expire date label'         => '到期日期',
'Expire date help'          => '这些禁止应该在何时自动移除（格式：yyyy-mm-dd）。留空以手动移除。',
'Ban IP label'              => '禁止 IP 地址',
'Ban IP help'               => '同时禁止被禁止用户的 IP 地址，使他们更难注册新账户。',
'Invalid date message'      => '您输入的到期日期无效。',
'Invalid date reasons'      => '格式应为 YYYY-MM-DD，日期必须至少在将来的一天。',
'Users banned redirect'     => '用户已被禁止。正在重定向 …',

'User search head'          => '用户搜索',
'User search subhead'       => '输入搜索条件',
'User search info'          => '在数据库中搜索用户。您可以输入一个或多个搜索条件。接受星号 (*) 作为通配符。',
'Username label'            => '用户名',
'E-mail address label'      => '电子邮件地址',
'Title label'               => '头衔',
'Real name label'           => '真实姓名',
'Website label'             => '网站',
'Jabber label'              => 'Jabber',
'ICQ label'                 => 'ICQ',
'Location label'            => '所在地',
'Signature label'           => '签名',
'Admin note label'          => '管理员备注',
'Posts more than label'     => '帖子数量大于',
'Posts less than label'     => '帖子数量小于',
'Last post after label'     => '最后一次发帖在',
'Date help'                 => '(yyyy-mm-dd hh:mm:ss)',
'Last post before label'    => '最后一次发帖在之前',
'Last visit after label'    => '最后一次访问在',
'Last visit before label'   => '最后一次访问在之前',
'Registered after label'    => '注册在',
'Registered before label'   => '注册在之前',
'Order by label'            => '排序依据',
'Order by username'         => '用户名',
'Order by e-mail'           => '电子邮件',
'Order by posts'            => '帖子数量',
'Order by last post'        => '最后一次发帖',
'Order by last visit'       => '最后一次访问',
'Order by registered'       => '注册时间',
'Ascending'                 => '升序',
'Descending'                => '降序',
'User group label'          => '用户组',
'All groups'                => '所有组',
'Unverified users'          => '未验证用户',
'Submit search'             => '提交搜索',
'IP search head'            => 'IP 搜索',
'IP search subhead'         => '输入要搜索的 IP',
'IP address label'          => 'IP 地址',
'IP address help'           => '在帖子数据库中搜索的 IP 地址。',
'Find IP address'           => '查找 IP 地址',

'Results head'              => '搜索结果',
'Results username head'     => '用户名',
'Results e-mail head'       => '电子邮件',
'Results title head'        => '头衔/状态',
'Results posts head'        => '帖子',
'Results admin note head'   => '管理员备注',
'Results actions head'      => '操作',
'Results IP address head'   => 'IP 地址',
'Results last used head'    => '最后使用',
'Results times found head'  => '找到次数',
'Results action head'       => '操作',
'Results find more link'    => '为此 IP 查找更多用户',
'Results no posts found'    => '当前没有该用户在论坛的帖子。',
'Select'                    => '选择',
'Select all'                => '全选',
'Unselect all'              => '全部取消选择',
'Ban'                       => '禁止',
'Delete'                    => '删除',
'Change group'              => '更改组',
'Bad IP message'            => '提供的 IP 地址格式不正确。',
'Results view IP link'      => '查看 IP 统计',
'Results show posts link'   => '显示帖子',
'Results guest'             => '访客',
'Results no IP found'       => '在数据库中找不到提供的 IP 地址。',
'No match'                  => '无匹配项'

);
