<?php

// 在 install.php 中使用的语言定义，由 adaur 本地化
$lang_install = array(

'Choose install language'        => '选择安装脚本的语言',
'Choose install language info'   => '用于此安装脚本的语言。下面的表单可以设置论坛本身的默认语言。',
'Install language'               => '安装语言',
'Change language'                => '更改语言',
'Already installed'              => '看起来 FluxBB 已经安装好了。你应该<a href="index.php">点这里</a>。',
'You are running error'          => '你正在运行 %1$s 版本 %2$s。FluxBB %3$s 至少需要 %1$s %4$s 才能正常运行。在继续之前，你必须升级你的 %1$s 安装。',
'My FluxBB Forum'                => '我的 FluxBB 论坛',
'Description'                    => '遗憾的是，没有人能被告知 FluxBB 是什么 - 你必须亲眼看看。',
'Username 1'                     => '用户名至少需要2个字符长。',
'Username 2'                     => '用户名不得超过25个字符长。',
'Username 3'                     => '用户名 guest 是保留的。',
'Username 4'                     => '用户名不能以 IP 地址的形式。',
'Username 5'                     => '用户名不能同时包含所有字符 \', " 和 [ 或 ]。',
'Username 6'                     => '用户名不能包含论坛使用的任何文本格式化标签（BBCode）。',
'Short password'                 => '密码至少需要9个字符长。',
'Passwords not match'            => '密码不匹配。',
'Wrong email'                    => '你输入的管理员电子邮件地址无效。',
'No board title'                 => '你必须输入一个论坛标题。',
'Error default language'         => '选择的默认语言似乎不存在。',
'Error default style'            => '选择的默认风格似乎不存在。',
'No DB extensions'               => '此 PHP 环境不支持 FluxBB 支持的任何数据库。PHP 需要支持 MySQL、PostgreSQL 或 SQLite 才能安装 FluxBB。',
'Administrator username'         => '管理员用户名',
'Administrator email'            => '管理员电子邮件',
'Board title'                    => '论坛标题',
'Base URL'                       => '你的 FluxBB 论坛的 URL（不带尾随斜杠）。这必须正确。',
'Required field'                 => '是这个表单中的必填字段。',
'FluxBB Installation'            => 'FluxBB 安装',
'Welcome'                        => '你即将安装 FluxBB。为了安装 FluxBB，你必须完成下面设置的表单。如果在安装过程中遇到任何困难，请参考文档。',
'Install'                        => '安装 FluxBB %s',
'Errors'                         => '需要更正以下错误：',
'Database setup'                 => '数据库设置',
'Info 1'                         => '我们需要的所有信息来创建与你的数据库的连接。',
'Select database'                => '选择你的数据库类型',
'Info 2'                         => '选择一个数据库。我们支持 SQLite、MySQL 和 PostgreSQL。',
'Database type'                  => '数据库类型',
'Required'                       => '(必填)',
'Database hostname'              => '输入你的数据库服务器主机名',
'Info 3'                         => '如果 <code>localhost</code> 不起作用，你应该能够从你的网络主机那里获得这些信息。',
'Database server hostname'       => '数据库服务器主机名',
'Database enter name'            => '输入你的数据库名称',
'Info 4'                         => '你想在哪个数据库上安装 FluxBB 的名称。',
'Database name'                  => '数据库名称',
'Database enter informations'    => '输入你的数据库用户名和密码',
'Database username'              => '数据库用户名',
'Info 5'                         => '你的 MySQL 用户名和密码（如果使用 SQLite 则忽略）。',
'Database password'              => '数据库密码',
'Database enter prefix'          => '输入数据库表前缀',
'Info 6'                         => '如果你想在单个数据库中运行多个 FluxBB 安装，请更改此设置。<b style="color:red;">对于 MySQL 8+，必须指定表前缀。</b>',
'Table prefix'                   => '表前缀',
'Administration setup'           => '管理设置',
'Info 7'                         => '创建论坛上的第一个账户。',
'Info 8'                         => '你的用户名应该在 2 到 25 个字符之间。你的密码必须至少 9 个字符长。记住密码是区分大小写的。',
'Password'                       => '密码',
'Confirm password'               => '确认密码',
'Board setup'                    => '论坛设置',
'Info 11'                        => '论坛的设置。你可以稍后更改这些。',
'General information'            => '输入你的论坛标题和描述。',
'Board description'              => '论坛描述（支持 HTML）',
'Appearance'                     => '外观',
'Info 15'                        => '使论坛成为你的。为你的论坛选择一种语言和风格。',
'Default language'               => '默认语言',
'Default style'                  => '默认风格',
'Start install'                  => '开始安装',
'DB type not valid'              => '"%s" 不是一个有效的数据库类型',
'Table prefix error'             => '表前缀 "%s" 包含非法字符或太长。前缀可以包含字母 a 到 z，任何数字和下划线。但是，它们不能以数字开头。最大长度为 40 个字符。请选择一个不同的前缀',
'Prefix reserved'                => '表前缀 "sqlite_" 是 SQLite 引擎保留使用的。请选择一个不同的前缀',
'Existing table error'           => '数据库 "%s" 中已经存在一个名为 "%susers" 的表。这可能意味着 FluxBB 已经安装，或者另一个软件已经安装并且占用了 FluxBB 需要的一个或多个表名。如果你想在同一个数据库中安装多个 FluxBB 副本，你必须选择一个不同的表前缀',
'InnoDB off'                     => 'InnoDB 似乎没有启用。请选择一个没有 InnoDB 支持的数据库层，或者在你的 MySQL 服务器上启用 InnoDB',
'Administrators'                 => '管理员',
'Administrator'                  => '管理员',
'Moderators'                     => '版主',
'Moderator'                      => '版主',
'Guests'                         => '访客',
'Guest'                          => '访客',
'Members'                        => '成员',
'Announcement'                   => '在这里输入你的公告。',
'Rules'                          => '在这里输入你的规则。',
'Maintenance message'            => '论坛暂时关闭进行维护。请稍后再试。',
'Test post'                      => '测试主题',
'Message'                        => '如果你正在看这个（我猜你是），FluxBB 的安装似乎已经成功了！现在登录并前往管理控制面板配置你的论坛。',
'Test category'                  => '测试分类',
'Test forum'                     => '测试论坛',
'This is just a test forum'      => '这只是个测试论坛',
'Alert cache'                    => '<strong>缓存目录当前不可写！</strong>为了让 FluxBB 正常工作，目录 <em>%s</em> 必须能够被 PHP 写入。使用 chmod 设置适当的目录权限。如果不确定，chmod 到 0777。',
'Alert avatar'                   => '<strong>头像目录当前不可写！</strong>如果你想让用户能够上传他们自己的头像图片，你必须确保目录 <em>%s</em> 能够被 PHP 写入。你可以稍后选择在不同的目录保存头像图片（见管理/选项）。使用 chmod 设置适当的目录权限。如果不确定，chmod 到 0777。',
'Alert upload'                   => '<strong>文件上传似乎在这台服务器上被禁止了！</strong>如果你想让用户能够上传他们自己的头像图片，你必须在 PHP 中启用 file_uploads 配置设置。一旦文件上传被启用，头像上传可以在管理/选项/功能中启用。',
'FluxBB has been installed'      => 'FluxBB 已经被安装。为了完成安装，请按照下面的说明进行。',
'Final instructions'             => '最终说明',
'Info 17'                        => '为了完成安装，你需要点击下面的按钮下载一个名为 config.php 的文件。然后你需要将这个文件上传到你的 FluxBB 安装的 /include 目录。',
'Info 18'                        => '一旦你上传了 config.php，FluxBB 将完全安装！那时，你可以 <a href="index.php">前往论坛首页</a>。',
'Download config.php file'       => '下载 config.php 文件',
'FluxBB fully installed'         => 'FluxBB 已经完全安装！你现在可以 <a href="index.php">前往论坛首页</a>。',

);
