<?php

$lang_pmsn = array(

'PM'                   => '私信',
'list'                 => '我的对话',
'listq'                => '对话处理中',
'new'                  => '新消息',
'newq'                 => '对话处理中',
'close'                => '私信功能已关闭',
'closeq'               => '确认关闭',
'save'                 => '保存消息',
'saveq'                => '移除对话',
'post'                 => '新建帖子',
'blocking'             => '阻止发送者',
'blocked'              => '已阻止用户',
'blockedq'             => '移除阻止',
'topic'                => '对话主题',
'del'                  => '删除',
'send'                 => '发送对话',
'edit'                 => '编辑帖子',

'mNew'                 => '新建',
'mList'                => '我的对话',
'mSave'                => '存档',

'Off'                  => '关闭私信',
'On'                   => '开启私信',
'Email on'             => '邮件通知：开启',
'Email off'            => '邮件通知：关闭',
'Email on Red'         => '邮件通知已开启。正在重定向 …',
'Email off Red'        => '邮件通知已关闭。正在重定向 …',

'Boxs'                 => '文件夹',
'Storage'              => '存储',
'Options'              => '选项',

'tDialog'              => '对话主题',
'tStarter'             => '发起人',
'tTo'                  => '收件人',
'tReplies'             => '回复数',
'tLast'                => '最后回复',

'Info zero'            => '此文件夹中没有对话。',
'Post new topic'       => '创建新对话',
'New dialog'           => '新对话',
'Addressee'            => '收件人',
'Dialog head'          => '对话标题',
'Save_'                => '存档',
'Save_Later'           => '存档（稍后发送）',
'Delete'               => '删除',
'Add Reply'            => '添加回复',
'Block'                => '阻止',
'Send d'               => '发送对话',

'Deleted'              => '已删除：',
'Yes'                  => ' 是 ',
'With'                 => ' 与 ',

'No subject'           => '主题必须包含标题。',
'Too long message'     => '帖子长度不能超过 65535 字节。',
'No addressee'         => '没有该用户名的用户。',
'No for itself'        => '不能给自己发送私信。',
'Off messages'         => '此用户已禁用私信功能。',
'More maximum'         => '该用户的文件夹已满。',
'More maximum user'    => '存档文件夹已满。',
'More maximum list'    => '我的对话文件夹已满。',
'Empty'                => '空。',
'No dialogs'           => '您没有选择任何对话进行处理。',
'Err1'                 => '选择了非您所有的对话。',
'Err2'                 => '您不能拥有那么多对话。',
'No block itself'      => '您不能阻止自己。',
'No block admin'       => '您不能阻止管理员。',
'Full folders'         => '您的文件夹已满。',
'No new post'          => '无法在此对话中添加新消息。',
'You block addr'       => '无法发送消息。您已阻止该用户。',
'Addr block you'       => '无法发送消息。该用户已阻止您。',
'No edit post'         => '此消息已被用户阅读过。',

'Info'                 => '信息',
'Info close'           => '您已关闭私信功能。',
'InfoQ'                => '确认关闭私信',
'InfoQ close'          => '警告！关闭私信将永久删除所有对话。',
'InfoQS'               => '关闭私信',
'Options redirect'     => '选项已更改。正在重定向 …',
'List redirect'        => '对话处理完成。正在重定向 …',
'InfoDeleteQ'          => '确认删除',
'InfoSaveQ'            => '确认保存',
'InfoDeleteQm'         => '您确定要删除选定的对话吗？',
'InfoSaveQm'           => '您确定要将选定的对话移动到存档吗？',
'InfoBlocking'         => '阻止该用户',
'InfoReBlocking'       => '移除对该用户的阻止',
'InfoReBlockingS'      => '移除对用户的阻止',
'InfoReBlockingSQ'     => '您确定要移除对选定用户的阻止吗？',
'InfoBlockingm'        => '您确定要阻止此用户给您发送私信吗？',
'InfoReBlockingm'      => '您确定要允许此用户给您发送私信吗？',
'Blocking redirect'    => '已添加阻止。正在重定向 …',
'ReBlocking redirect'  => '已移除阻止。正在重定向 …',
'Topic review'         => '主题回顾（最新优先）',
'InfoDeleteMes'        => '您确定要从此对话 “%s” 中删除此消息吗？',
'InfoDeleteTop'        => '您确定要删除此对话 “%s” 吗？',
'DelTop redirect'      => '对话已移除。正在重定向 …',
'DelMes redirect'      => '消息已移除。正在重定向 …',
'InfoDeleteQMes'       => '确认从此对话中移除此消息',
'InfoDeleteQTop'       => '确认从此对话中移除',
'InfoSend'             => '正在发送对话 “%s”',
'InfoSendQ'            => '发送对话给用户 <strong>%s</strong>?',
'Attention'            => '注意！！！',
'Delete dialog'        => '删除与此用户之间的对话',

'Modul failed message' => '模块 “%s” 加载失败。',
'No modul message'     => '没有名为 “%s” 的模块。',
'Min post'             => '您必须在论坛中至少发表 %s 篇帖子才能发送私信。',
'Warn'                 => '<b>注意！！！</b><br />在此用户在论坛中至少发表 %s 篇帖子之前，您将不会收到回复。',

);
