<?php

// 在 profile.php 中使用的语言定义
$lang_profile = array(

// 导航和部分
'Profile menu'               => '个人资料菜单',
'Section essentials'         => '基本信息',
'Section personal'           => '个人信息',
'Section messaging'          => '消息',
'Section personality'        => '个性',
'Section display'            => '显示',
'Section privacy'            => '隐私',
'Section admin'              => '管理',

// 其他
'Username and pass legend'    => '输入您的用户名和密码',
'Personal details legend'     => '输入您的个人详细信息',
'Contact details legend'      => '输入您的消息联系信息',
'User activity'               => '用户活动',
'Paginate info'               => '输入您希望在每个页面上查看的主题和帖子的数量',

// 密码相关
'Pass key bad'                => '指定的密码激活密钥不正确或已过期。请重新请求新密码。如果失败，请联系论坛管理员。',
'Pass updated'                => '您的密码已更新。现在您可以使用新密码登录。',
'Pass updated redirect'       => '密码已更新。正在重定向…',
'Wrong pass'                  => '旧密码错误。',
'Change pass'                 => '更改密码',
'Change pass legend'          => '输入并确认您的新密码',
'Old pass'                    => '旧密码',
'New pass'                    => '新密码',
'Confirm new pass'            => '确认新密码',
'Pass info'                   => '密码至少需要9个字符长。密码区分大小写。',

// 电子邮件相关
'Email key bad'               => '指定的电子邮件激活密钥不正确或已过期。请重新请求更改电子邮件地址。如果失败，请联系论坛管理员。',
'Email updated'               => '您的电子邮件地址已更新。',
'Activate email sent'         => '一封带有激活新电子邮件地址说明的电子邮件已发送到指定地址。如果没有收到，您可以联系论坛管理员。',
'Email legend'                => '输入您的新电子邮件地址',
'Email instructions'          => '一封电子邮件将发送到您的新地址，其中包含一个激活链接。您必须点击收到的电子邮件中的链接以激活新地址。',
'Change email'                => '更改电子邮件地址',
'New email'                   => '新电子邮件',

// 头像上传相关
'Avatars disabled'            => '管理员已禁用头像支持。',
'Too large ini'               => '选择的文件太大，无法上传。服务器不允许上传。',
'Partial upload'              => '选择的文件只上传了部分。请再试一次。',
'No tmp directory'            => 'PHP 无法将上传的文件保存到临时位置。',
'No file'                     => '您没有选择上传的文件。',
'Bad type'                    => '您尝试上传的文件类型不允许。允许的类型有 gif、jpeg 和 png。',
'Too wide or high'            => '您尝试上传的文件比允许的最大尺寸宽和/或高',
'Too large'                   => '您尝试上传的文件比允许的最大尺寸大',
'pixels'                      => '像素',
'bytes'                       => '字节',
'Move failed'                 => '服务器无法保存上传的文件。请联系论坛管理员。',
'Unknown failure'             => '发生了未知错误。请再试一次。',
'Avatar upload redirect'      => '头像已上传。正在重定向…',
'Avatar deleted redirect'     => '头像已删除。正在重定向…',
'Avatar desc'                 => '头像是显示在您的帖子中用户名下方的小图像。它不能比',
'Upload avatar'               => '上传头像',
'Upload avatar legend'        => '输入要上传的头像文件',
'Delete avatar'               => '删除头像', // 仅限管理员
'File'                        => '文件',
'Upload'                      => '上传', // 提交按钮

// 表单验证相关
'Forbidden title'             => '您输入的标题包含禁止的词。您必须选择不同的标题。',
'Profile redirect'            => '个人资料已更新。正在重定向…',

// 个人资料展示相关
'Users profile'               => '%s 的个人资料',
'Username info'               => '用户名：%s',
'Email info'                  => '电子邮件：%s',
'Posts info'                  => '帖子：%s',
'Registered info'             => '注册时间：%s',
'Last post info'              => '上次发帖：%s',
'Last visit info'             => '上次访问：%s',
'Show posts'                  => '显示所有帖子',
'Show topics'                 => '显示所有主题',
'Show subscriptions'          => '显示所有订阅',
'Realname'                    => '真实姓名',
'Location'                    => '所在地',
'Website'                     => '网站',
'Invalid website URL'         => '您输入的网站 URL 无效。',
'Website not allowed'         => '您尚未被允许在个人资料中添加网站。',
'Jabber'                      => 'Jabber',
'ICQ'                         => 'ICQ',
'Avatar'                      => '头像',
'Signature'                   => '签名',
'Sig max size'                => '最大长度：%s 字符 / 最大行数：%s',
'Avatar legend'               => '设置您的头像显示选项',
'Avatar info'                 => '头像是会与您所有帖子一起显示的小图像。您可以通过点击下面的链接上传头像。',
'Change avatar'               => '更改头像',
'Signature legend'            => '撰写您的签名',
'Signature info'              => '签名是附加在您的帖子上的一小段文本。在其中，您可以输入几乎所有您喜欢的内容。也许您想输入您最喜欢的引用或星座。由您决定！在您的签名中，如果论坛允许，您可以使用 BBCode。您可以随时在编辑签名时查看下面列出的允许/启用的功能。',
'Sig preview'                 => '当前签名预览：',
'No sig'                      => '个人资料中当前没有存储签名。',
'Signature quote/code/list/h' => '签名中不允许使用 quote、code、hr、size、audio、video、list、spoiler 和 heading BBCode。',
'Topics per page'             => '每页主题数',
'Posts per page'              => '每页帖子数',
'Leave blank'                 => '留空以使用论坛默认设置。',
'Subscription legend'         => '设置您的订阅选项',
'Notify full'                 => '在订阅通知邮件中包含新帖子的纯文本版本。',
'Auto notify full'            => '自动订阅您参与的每个主题。',
'Show smilies'                => '显示表情图标。',
'Show images'                 => '在帖子中显示图片。',
'Show images sigs'            => '在用户签名中显示图片。',
'Show avatars'                => '在帖子中显示用户头像。',
'Show sigs'                   => '显示用户签名。',
'Style legend'                => '选择您喜欢的风格',
'Styles'                      => '风格',
'Admin note'                  => '管理员备注',
'Pagination legend'           => '输入您的分页选项',
'Post display legend'         => '设置帖子查看选项',
'Post display info'           => '如果您的连接速度较慢，禁用这些选项，特别是帖子和签名中的图片显示，将使页面加载更快。',
'Instructions'                => '当您更新个人资料时，您将被重定向回此页面。',

// 管理相关
'Group membership legend'    => '选择用户组',
'Save'                       => '保存',
'Set mods legend'            => '设置版主访问',
'Moderator in info'          => '选择此用户应该被允许管理哪些论坛。注意：这只适用于版主。管理员在所有论坛中始终拥有完全权限。',
'Update forums'              => '更新论坛',
'Delete ban legend'          => '删除（仅限管理员）或禁止用户',
'Delete user'                => '删除用户',
'Ban user'                   => '禁止用户',
'Confirm delete legend'      => '重要：在删除用户前阅读',
'Confirm delete user'        => '确认删除用户',
'Confirmation info'          => '请确认您想要删除用户', // 用户名将附加到此字符串
'Delete warning'             => '警告！删除的用户和/或帖子无法恢复。如果您选择不删除此用户发表的帖子，这些帖子只能在以后手动删除。',
'Delete posts'               => '删除此用户发表的任何帖子和主题。',
'Delete'                     => '删除', // 确认用户删除的提交按钮
'User delete redirect'       => '用户已删除。正在重定向…',
'User promote redirect'      => '用户已晋升。正在重定向…',
'Group membership redirect'  => '用户组成员身份已保存。正在重定向…',
'Update forums redirect'     => '论坛版主权限已更新。正在重定向…',
'Ban redirect'               => '正在重定向…',
'No delete admin message'    => '管理员不能被删除。要删除此用户，您必须先将他/她移动到不同的用户组。',

);
