<?php

// 在 search.php 中使用的语言定义
$lang_search = array(

// 搜索表单
'User search'              => '用户搜索',
'No search permission'     => '您没有使用搜索功能的权限。',
'Search flood'             => '搜索之间至少需要间隔 %s 秒。请等待 %s 秒后再尝试搜索。',
'Search'                    => '搜索',
'Search criteria legend'    => '输入您的搜索条件',
'Search info'              => '要按关键词搜索，请输入要搜索的一个或多个术语。用空格分隔术语。使用 AND, OR 和 NOT 来优化您的搜索。要按作者搜索，请输入您希望搜索的帖子的作者的用户名。使用通配符 * 进行部分匹配。',
'Keyword search'            => '关键词搜索',
'Author search'            => '作者搜索',
'Search in legend'         => '选择搜索位置',
'Search in info'           => '选择您希望搜索的论坛，以及是否要在主题标题、消息文本或两者中搜索。',
'Search multiple forums info'=> '如果没有选择论坛，将搜索所有论坛。',
'Forum search'              => '论坛',
'Search in'                 => '搜索范围',
'Message and subject'      => '消息文本和主题标题',
'Message only'              => '仅消息文本',
'Topic only'                => '仅主题标题',
'Sort by'                   => '排序依据',
'Sort order'                => '排序方式',
'Search results legend'     => '选择查看搜索结果的方式',
'Search results info'       => '您可以选择您希望如何排序和显示您的结果。',
'Sort by post time'        => '按帖子时间排序',
'Sort by author'            => '按作者排序',
'Sort by subject'           => '按主题排序',
'Sort by forum'             => '按论坛排序',
'Ascending'                 => '升序',
'Descending'                => '降序',
'Show as'                   => '显示结果为',
'Show as topics'           => '主题',
'Show as posts'             => '帖子',

// 结果
'Search'                    => '搜索',
'Search results'            => '搜索结果',
'Quick search show_new'     => '最新',
'Quick search show_recent' => '活跃',
'Quick search show_unanswered' => '未回答',
'Quick search show_replies' => '已发布',
'Quick search show_user_topics' => '%s 的主题',
'Quick search show_user_posts' => '%s 的帖子',
'Quick search show_subscriptions' => '%s 订阅的',
'Quick search show_user_warn' => '%s 的警告',
'By keywords show as topics' => '包含关键词 \'%s\' 的主题',
'By keywords show as posts' => '包含关键词 \'%s\' 的帖子',
'By user show as topics' => '%s 发布的主题',
'By user show as posts' => '%s 发布的帖子',
'By both show as topics' => '包含关键词 \'%s\' 且由 %s 发布的主题',
'By both show as posts' => '包含关键词 \'%s\' 且由 %s 发布的帖子',
'No terms'                  => '您至少需要输入一个关键词和/或一个作者来进行搜索。搜索词至少需要三个字符长。',
'No hits'                   => '您的搜索没有找到匹配的结果。',
'No user posts'             => '该用户在此论坛中没有帖子。',
'No user topics'            => '该用户在此论坛中没有主题。',
'No subscriptions'          => '该用户当前没有订阅任何主题。',
'No new posts'              => '自您上次访问以来没有新帖子的主题。',
'No recent posts'           => '在过去的24小时内没有新帖子。',
'No unanswered'              => '此论坛中没有未回答的帖子。',
'Go to post'                => '转到帖子',
'Go to topic'               => '转到主题'

);
