<?php

$lang_up = array(
'No upfiles'                 => '没有文件上传。',
'Error'                      => '<strong>错误</strong>：',
'Error DB'                   => '无法插入表 %s',
'Error DB ins-up'            => '数据库插入/更新错误',
'Error space'                => '您超出了存储空间。请删除文件后重试。',
'Error delete'               => '文件删除时出错。',
'Error img'                  => '图片格式无效。或者服务器不支持图片处理。',
'Error no mod img'           => '图片更新时崩溃。',
'Error open'                 => '上传的文件无法打开。',
'Error inject'               => '上传的文件包含禁止的字符串。请归档此文件后重试，或联系管理员。',
'Error usage'                => '文件在 %d 个帖子中使用。',

'Redirect'                   => '选项已更新。正在重定向 …',
'Install info'               => '准备数据库和缓存以操作 Uploadile。',
'Install'                    => '安装',
'Update info'                => '更新缓存。（默认值）',
'Update'                     => '更新',
'Uninstall info'             => '恢复数据库并修改缓存以卸载 Uploadile。',
'Uninstall'                  => '卸载',

'configuration'              => '配置',
'plugin_desc'                => '此插件提供了文件上传操作的功能。',
'legend_2'                   => '图片设置',
'laws'                       => '允许的文件类型。用逗号 (,) 分隔。',
'thumb'                      => '激活缩略图',
'thumb_size'                 => '缩略图大小：',
'quality'                    => '质量：',
'maxsize_member'             => '会员可上传的最大文件大小（兆字节）。',
'limit_member'               => '分配给会员的空间（兆字节）。',
'allow_delete'               => '允许删除在帖子中使用的文件。',
'px'                         => '像素',
'kbytes'                     => '千字节',
'pictures'                   => '图片',
'for pictures'               => '对于大于',
'Install quality'            => '安装质量：',
'Size not more'              => '大小不超过 (WxH)：',
'to jpeg'                    => '转换为 jpeg',

'Redirect delete'            => '文件已成功删除。正在重定向 …',
'Redirect upload'            => '文件已上传。正在重定向 …',

'uploadile'                  => '我的上传',
'titre_2'                    => '上传文件',
'titre_4'                    => '我的上传',
'popup_title'                => '文件管理器',

'info_2'                     => '%1$s （最大文件大小 %2$s）',
'info_4'                     => '已使用的存储空间：<span>%s</span>，允许的最大空间为 %s。',
'legend'                     => '文件',
'fichier'                    => '选择一个文件',

'th0'                        => '用户名',
'th1'                        => '文件名',
'th2'                        => '预览',
'no_preview'                 => '无',
'Member files'               => '会员文件（新的在上面）',

'legend_1'                   => '转换',
'convert'                    => '转换',
'mo'                         => '以 MB 为单位的值',
'ko'                         => '以 KB 为单位的值',
'o'                          => '以 B 为单位的值',
'texte'                      => '这里输入您的文本',
'delete'                     => '删除',
'delete file'                => '您要删除此文件吗？',
'insert'                     => '插入',
'insert_thumb'               => '插入缩略图',
'update_thumb'               => '更新缩略图',

'upfiles'                    => '上传文件',

'groups'                     => '组的调整',
'group'                      => '组',

// 头像上传相关
'Bad type'                   => '您尝试上传的文件类型不允许。',
'Too large'                  => '您尝试上传的文件超过了最大允许大小。',
'Move failed'                => '服务器无法保存上传的文件。',
'Unknown failure'            => '发生了未知错误。',
'Upload'                     => '上传',

'UPLOAD_ERR_INI_SIZE'        => '上传的文件超过了 php.ini 中 upload_max_filesize 指令的限制。',
'UPLOAD_ERR_FORM_SIZE'       => '上传的文件超过了 HTML 表单中指定的 MAX_FILE_SIZE 指令。',
'UPLOAD_ERR_PARTIAL'         => '上传的文件仅部分上传。',
'UPLOAD_ERR_NO_FILE'         => '没有文件被上传。',
'UPLOAD_ERR_NO_TMP_DIR'      => '缺少临时文件夹。',
'UPLOAD_ERR_CANT_WRITE'      => '写入磁盘失败。',
'UPLOAD_ERR_EXTENSION'       => 'PHP 扩展停止了文件上传。',
'UPLOAD_ERR_UNKNOWN'         => '未知的上传错误。',

'Deleting file'              => '正在删除文件',
'%s file'                    => '<b>%s</b> 文件',
'Bad file extensions'        => '错误的文件扩展名：%s。<br />',
);
